import { BookOpen, Bot, CreditCard, Database, FolderOpen, Keyboard, Play, RefreshCw, Sparkles } from 'lucide-react';
import AIKeyGuide from '../AIKeyGuide';
import type { TourDefinition } from '../types';

/** The first-run tour: about ten steps, one of them something the user does. Everything else lives in the page tours. */
export const onboardingTour: TourDefinition = {
  id: 'onboarding',
  title: 'Bun venit',
  steps: [
    {
      id: 'welcome',
      title: 'Bun venit în StudyX',
      body: 'Grile, flashcarduri cu repetare spațiată și o bibliotecă AI care citește cursurile tale. Turul durează aproximativ 2 minute și îl poți închide oricând.',
      icon: <Sparkles size={22} />,
      placement: 'center',
      route: '/',
      accent: '#0A84FF',
    },
    {
      id: 'sidebar',
      title: 'Totul pornește din bara laterală',
      body: 'Sus ai Studiu (grile, recapitulare, statistici), dedesubt Resurse (notițe, Biblioteca AI), apoi folderele tale, câte unul pentru fiecare materie. „Restrânge” îi dă mai mult loc paginii.',
      icon: <FolderOpen size={22} />,
      target: '[data-tutorial="sidebar"]',
      targetPadding: 8,
      placement: 'right',
      route: '/',
    },
    {
      id: 'first-quiz',
      title: 'Prima ta grilă',
      body: 'Creează una de la zero sau importă una existentă: dintr-un fișier sau generată din cursurile tale. Încearcă acum.',
      icon: <BookOpen size={22} />,
      target: '[data-tutorial="btn-new-quiz"]',
      targetPadding: 6,
      placement: 'bottom',
      route: '/',
      accent: '#30D158',
      completeWhen: (ctx, atEntry) => ctx.quizCount > atEntry.quizCount,
      actionHint: 'Apasă „Creează grilă” sau importă una. Turul continuă singur, sau sari peste.',
    },
    {
      id: 'play-modes',
      title: 'Patru moduri de joc',
      body: 'Studiu: feedback imediat și explicații.\nExamen: fără feedback, scorul la final.\nCronometrat: timp limitat pe întrebare.\nRezidențiat: penalizare pentru răspunsul greșit, ca la examen.',
      icon: <Play size={22} />,
      placement: 'center',
      accent: '#5E5CE6',
    },
    {
      id: 'flashcards-new',
      title: 'Flashcarduri',
      body: 'Aici creezi primele pachete: din cursurile tale, din greșelile tale sau din import. Când ai carduri, „De repetat azi” îți arată exact ce ai de făcut.',
      icon: <CreditCard size={22} />,
      target: '[data-tutorial="flashcards-create"]',
      targetPadding: 6,
      placement: 'top',
      route: '/flashcards',
      accent: '#BF6FFF',
      when: (ctx) => ctx.deckCount === 0,
    },
    {
      id: 'flashcards',
      title: 'Flashcarduri',
      body: '„De repetat azi” strânge într-un loc cardurile scadente și pe cele noi. Dedesubt sunt pachetele tale, iar „Creează pachet nou” le face din cursurile tale, din greșeli sau din import.',
      icon: <CreditCard size={22} />,
      target: '[data-tutorial="flashcards-due"]',
      targetPadding: 6,
      placement: 'bottom',
      route: '/flashcards',
      accent: '#BF6FFF',
      when: (ctx) => ctx.deckCount > 0,
    },
    {
      id: 'spaced-repetition',
      title: 'Repetarea care se adaptează',
      body: 'La fiecare card alegi Greu, Bine sau Ușor (tastele 1, 2, 3). Pe ce știi bine îl vezi tot mai rar, pe ce greșești revine curând. Studiezi puțin în fiecare zi, nu mult odată.',
      icon: <RefreshCw size={22} />,
      target: '[data-tutorial="nav-daily-review"]',
      targetPadding: 6,
      placement: 'right',
      route: '/',
      accent: '#FF9F0A',
    },
    {
      id: 'vault',
      title: 'Biblioteca AI',
      body: 'Încarci cursuri (PDF, DOCX, poze) și AI-ul le indexează. De acolo, răspunsurile și grilele generate pornesc din cursurile tale și arată din ce fragment vin.',
      icon: <Database size={22} />,
      target: '[data-tutorial="nav-vault"]',
      targetPadding: 6,
      placement: 'right',
      route: '/',
      accent: '#64D2FF',
    },
    {
      id: 'ai-key',
      title: 'AI-ul tău, gratuit',
      body: 'Cu o cheie gratuită, StudyX generează carduri și grile din cursuri și îți răspunde în chat.',
      icon: <Bot size={22} />,
      placement: 'center',
      accent: '#BF6FFF',
      Extra: () => <AIKeyGuide />,
    },
    {
      id: 'chat',
      title: 'Chat și agent',
      body: 'Scrie ce vrei, în română, de exemplu „fă-mi 5 grile din mielom multiplu”. Agentul arată fiecare pas și îl poți opri oricând.',
      icon: <Bot size={22} />,
      target: '[data-tutorial="ai-chat-button"]',
      targetPadding: 8,
      placement: 'left',
      route: '/',
      accent: '#BF6FFF',
    },
    {
      id: 'finish',
      title: 'Căutare, scurtături și backup',
      body: 'Ctrl+K caută instant în grilele tale, iar ? arată scurtăturile de tastatură. Din Setări exporți oricând un backup. Pe paginile cu „?” lângă titlu găsești câte un tur scurt.',
      icon: <Keyboard size={22} />,
      target: '[data-tutorial="global-search"]',
      targetPadding: 8,
      placement: 'bottom',
      route: '/',
      accent: '#0A84FF',
    },
  ],
};
